### PR TITLE
Added multi-package support

### PR DESCRIPTION
**Pull request by DUFCLiam**
Added the ability to use multi-packages/classes; This is not fully working yet I need a way to register all things with the prefix `C_<COMMANDS NAME>` that I forgot how to do.

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
Spelt my name wrong, stephenbullough. Not Steven.

**Comment by DUFCLiam** [comment]
Oops xD Fixed

**Comment by LegendIsAwesomes** [comment]
I'll merge this but next time don't copy TFM, if possible make it so you don't have to define cmds in the plugin.yml

**Comment by DUFCLiam** [comment]
Ok, I used TFM's one for quickness.

**Comment by DUFCLiam** [comment]
I will try and use `@` annotations maybe

`@Description = "Description"`

**Comment by LegendIsAwesomes** [comment]
Thanks for contributing

**Comment by DUFCLiam** [comment]
You're welcome.

**Comment by LegendIsAwesomes** [comment]
Now make it so cmds don't  have to be defined in the plugin.yml like tfm :)

**Comment by DUFCLiam** [comment]
I will try, Permission to use the `@` annotations from TFM?

**Comment by LegendIsAwesomes** [comment]
I'll review it.

**Comment by DUFCLiam** [comment]
Ok.

**Comment by DUFCLiam** [comment]
Can you create a permission system?

**Comment by DUFCLiam** [comment]
Or will I try and do that?

**Comment by LegendIsAwesomes** [comment]
Like the TFM_CommandLoader in the commands package in TFM.

**Comment by DUFCLiam** [comment]
Yeah, but like TFM has super admins we can have something else can you sort our ranks please?

**Comment by LegendIsAwesomes** [comment]
Ill do ranks I want you to make something like the TFM_CommandHandler and the TFM_CommandLoader.

**Comment by DUFCLiam** [comment]
Okay

**Pull request merged**
