### PR TITLE
New PR

### PR DESCRIPTION
**Pull request by DUFCLiam**
- [x] TODO:
    - [x] Added the things in .github
    - [x] Added variables in `immafreedommod.java`
    - [x] Updated `plugin.yml`
    - [x] Merged #5

### CODE REVIEW

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes

**Comment by DUFCLiam** [comment]
Will fix.

**Comment by DUFCLiam** [comment]
Ready to merge @LegendIsAwesomes.

**Comment by LegendIsAwesomes** [comment]
Thanks for contributing, hoping to see more PRs

**Comment by DUFCLiam** [comment]
Thank you :)

**Pull request merged**
