### PR TITLE
Update immafreedommod.java

### PR DESCRIPTION
**Pull request by DUFCLiam**

### CODE REVIEW

**Comment by LegendIsAwesomes** [comment]
No.

**Comment by DUFCLiam** [comment]
Ok.

**Comment by DUFCLiam** [comment]
May you look at #3 and #5  now please?

**Comment by LegendIsAwesomes** [comment]
Already have, Ill review soon

**Comment by DUFCLiam** [comment]
Ok :)

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes Can I be a  collaborator on this repo? I will make PRs though.

**Comment by LegendIsAwesomes** [comment]
No just make prs

**Comment by DUFCLiam** [comment]
Okay :+1:

**Pull request closed without merging**
